[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"

[packages]
apt = ["libnss3", "libatk-bridge2.0-0", "libx11-xcb1", "libxcomposite1", "libxcursor1", "libxdamage1", "libxrandr2", "libgbm1", "libasound2", "libpangocairo-1.0-0", "libatk1.0-0", "libgtk-3-0", "libdrm2", "libxfixes3"]
